### ISSUE TITLE
二阶段检测方法的支持

### ISSUE THREAD

**Issue by maxin-cn** [Ben-Louis/FisherPruning-Pytorch#3]
感谢您复现这个code，我想请问下该方法是否支持二阶段的检测方法呢，比如cascade_mask_rcnn之类的。多谢！

**Comment by Ben-Louis** [comment]
照理说是支持的，二阶段检测模型像 faster-rcnn 可以成功运行。cascade_mask_rcnn 我没试过，你可以试一下 :D

**Comment by maxin-cn** [comment]
> 照理说是支持的，二阶段检测模型像 faster-rcnn 可以成功运行。cascade_mask_rcnn 我没试过，你可以试一下 :D

好的，感谢回复！

**Comment by maxin-cn** [comment]
> faster-rcnn

我跑faster-rcnn的时候遇到了以下的问题，请问下是什么原因呢？我的环境用的是:
torch 1.8.0
mmcv 1.3.16
mmdet 2.13.0
torchvision 0.9.0
cudatoolkit 10.2
我同样尝试了mmdet 2.17.0的版本，遇到了相同的错误
```
Traceback (most recent call last):
  File "tools/train.py", line 195, in <module>
Traceback (most recent call last):
  File "tools/train.py", line 195, in <module>
    main()
  File "tools/train.py", line 191, in main
    main()
  File "tools/train.py", line 191, in main
    meta=meta)
  File "/mmdet/apis/train.py", line 170, in train_detector
    meta=meta)
  File "/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
    self.call_hook('after_train_iter')
  File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/hooks/optimizer.py", line 35, in after_train_iter
    runner.outputs['loss'].backward()
  File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
  File "/FisherPruning-Pytorch-main/detection/tools/fisher_pruning_hook/fisher_pruning.py", line 397, in compute_fisher_backward_hook
    runner.run(data_loaders, cfg.workflow)
  File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
    self.call_hook('after_train_iter')
  File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/hooks/optimizer.py", line 35, in after_train_iter
    runner.outputs['loss'].backward()
  File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
  File "/FisherPruning-Pytorch-main/detection/tools/fisher_pruning_hook/fisher_pruning.py", line 397, in compute_fisher_backward_hook
    grads = feature * grad_feature
RuntimeError: The size of tensor a (256) must match the size of tensor b (12) at non-singleton dimension 1
    grads = feature * grad_feature
RuntimeError: The size of tensor a (256) must match the size of tensor b (12) at non-singleton dimension 1
Killing subprocess 35929
Killing subprocess 35930
Traceback (most recent call last):
  File "/anaconda3/envs/fisher/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/envs/fisher/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/workdir/maxin/anaconda3/envs/fisher/bin/python', '-u', 'tools/train.py', '--local_rank=1', 'configs/faster_rcnn/faster_pruning.py', '--launch', 'pytorch']' returned non-zero exit status 1.
```

**Comment by zhaoxin111** [comment]
> > faster-rcnn
> 
> 我跑faster-rcnn的时候遇到了以下的问题，请问下是什么原因呢？我的环境用的是: torch 1.8.0 mmcv 1.3.16 mmdet 2.13.0 torchvision 0.9.0 cudatoolkit 10.2 我同样尝试了mmdet 2.17.0的版本，遇到了相同的错误
> 
> ```
> Traceback (most recent call last):
>   File "tools/train.py", line 195, in <module>
> Traceback (most recent call last):
>   File "tools/train.py", line 195, in <module>
>     main()
>   File "tools/train.py", line 191, in main
>     main()
>   File "tools/train.py", line 191, in main
>     meta=meta)
>   File "/mmdet/apis/train.py", line 170, in train_detector
>     meta=meta)
>   File "/mmdet/apis/train.py", line 170, in train_detector
>     runner.run(data_loaders, cfg.workflow)
>   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
>     epoch_runner(data_loaders[i], **kwargs)
>   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
>     self.call_hook('after_train_iter')
>   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
>     getattr(hook, fn_name)(self)
>   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/hooks/optimizer.py", line 35, in after_train_iter
>     runner.outputs['loss'].backward()
>   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/tensor.py", line 245, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
>   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/autograd/__init__.py", line 147, in backward
>     allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
>   File "/FisherPruning-Pytorch-main/detection/tools/fisher_pruning_hook/fisher_pruning.py", line 397, in compute_fisher_backward_hook
>     runner.run(data_loaders, cfg.workflow)
>   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
>     epoch_runner(data_loaders[i], **kwargs)
>   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
>     self.call_hook('after_train_iter')
>   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
>     getattr(hook, fn_name)(self)
>   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/hooks/optimizer.py", line 35, in after_train_iter
>     runner.outputs['loss'].backward()
>   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/tensor.py", line 245, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
>   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/autograd/__init__.py", line 147, in backward
>     allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
>   File "/FisherPruning-Pytorch-main/detection/tools/fisher_pruning_hook/fisher_pruning.py", line 397, in compute_fisher_backward_hook
>     grads = feature * grad_feature
> RuntimeError: The size of tensor a (256) must match the size of tensor b (12) at non-singleton dimension 1
>     grads = feature * grad_feature
> RuntimeError: The size of tensor a (256) must match the size of tensor b (12) at non-singleton dimension 1
> Killing subprocess 35929
> Killing subprocess 35930
> Traceback (most recent call last):
>   File "/anaconda3/envs/fisher/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/anaconda3/envs/fisher/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
>     main()
>   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
>     sigkill_handler(signal.SIGTERM, None)  # not coming back
>   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
>     raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
> subprocess.CalledProcessError: Command '['/workdir/maxin/anaconda3/envs/fisher/bin/python', '-u', 'tools/train.py', '--local_rank=1', 'configs/faster_rcnn/faster_pruning.py', '--launch', 'pytorch']' returned non-zero exit status 1.
> ```

torch升级到1.10看看

**Comment by Janspiry** [comment]
> > > faster-rcnn
> > 
> > 
> > 我跑faster-rcnn的时候遇到了以下的问题，请问下是什么原因呢？我的环境用的是: torch 1.8.0 mmcv 1.3.16 mmdet 2.13.0 torchvision 0.9.0 cudatoolkit 10.2 我同样尝试了mmdet 2.17.0的版本，遇到了相同的错误
> > ```
> > Traceback (most recent call last):
> >   File "tools/train.py", line 195, in <module>
> > Traceback (most recent call last):
> >   File "tools/train.py", line 195, in <module>
> >     main()
> >   File "tools/train.py", line 191, in main
> >     main()
> >   File "tools/train.py", line 191, in main
> >     meta=meta)
> >   File "/mmdet/apis/train.py", line 170, in train_detector
> >     meta=meta)
> >   File "/mmdet/apis/train.py", line 170, in train_detector
> >     runner.run(data_loaders, cfg.workflow)
> >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
> >     epoch_runner(data_loaders[i], **kwargs)
> >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
> >     self.call_hook('after_train_iter')
> >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
> >     getattr(hook, fn_name)(self)
> >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/hooks/optimizer.py", line 35, in after_train_iter
> >     runner.outputs['loss'].backward()
> >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/tensor.py", line 245, in backward
> >     torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
> >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/autograd/__init__.py", line 147, in backward
> >     allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
> >   File "/FisherPruning-Pytorch-main/detection/tools/fisher_pruning_hook/fisher_pruning.py", line 397, in compute_fisher_backward_hook
> >     runner.run(data_loaders, cfg.workflow)
> >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
> >     epoch_runner(data_loaders[i], **kwargs)
> >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
> >     self.call_hook('after_train_iter')
> >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
> >     getattr(hook, fn_name)(self)
> >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/hooks/optimizer.py", line 35, in after_train_iter
> >     runner.outputs['loss'].backward()
> >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/tensor.py", line 245, in backward
> >     torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
> >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/autograd/__init__.py", line 147, in backward
> >     allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
> >   File "/FisherPruning-Pytorch-main/detection/tools/fisher_pruning_hook/fisher_pruning.py", line 397, in compute_fisher_backward_hook
> >     grads = feature * grad_feature
> > RuntimeError: The size of tensor a (256) must match the size of tensor b (12) at non-singleton dimension 1
> >     grads = feature * grad_feature
> > RuntimeError: The size of tensor a (256) must match the size of tensor b (12) at non-singleton dimension 1
> > Killing subprocess 35929
> > Killing subprocess 35930
> > Traceback (most recent call last):
> >   File "/anaconda3/envs/fisher/lib/python3.7/runpy.py", line 193, in _run_module_as_main
> >     "__main__", mod_spec)
> >   File "/anaconda3/envs/fisher/lib/python3.7/runpy.py", line 85, in _run_code
> >     exec(code, run_globals)
> >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
> >     main()
> >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
> >     sigkill_handler(signal.SIGTERM, None)  # not coming back
> >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
> >     raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
> > subprocess.CalledProcessError: Command '['/workdir/maxin/anaconda3/envs/fisher/bin/python', '-u', 'tools/train.py', '--local_rank=1', 'configs/faster_rcnn/faster_pruning.py', '--launch', 'pytorch']' returned non-zero exit status 1.
> > ```
> 
> torch升级到1.10看看

@zhaoxin111 Hi,  我升级了之后还是出现该错误，我的环境是：
  - PyTorch: 1.10.1+cu113
  - GCC 7.3
  - CUDA Runtime 11.3
  - CuDNN 8.2
  - TorchVision: 0.11.2+cu113
  

方便展示一下你的环境吗？

**Comment by zhaoxin111** [comment]
> 

你是什么卡呢

**Comment by zhaoxin111** [comment]
> > > > faster-rcnn
> > > 
> > > 
> > > 我跑faster-rcnn的时候遇到了以下的问题，请问下是什么原因呢？我的环境用的是: torch 1.8.0 mmcv 1.3.16 mmdet 2.13.0 torchvision 0.9.0 cudatoolkit 10.2 我同样尝试了mmdet 2.17.0的版本，遇到了相同的错误
> > > ```
> > > Traceback (most recent call last):
> > >   File "tools/train.py", line 195, in <module>
> > > Traceback (most recent call last):
> > >   File "tools/train.py", line 195, in <module>
> > >     main()
> > >   File "tools/train.py", line 191, in main
> > >     main()
> > >   File "tools/train.py", line 191, in main
> > >     meta=meta)
> > >   File "/mmdet/apis/train.py", line 170, in train_detector
> > >     meta=meta)
> > >   File "/mmdet/apis/train.py", line 170, in train_detector
> > >     runner.run(data_loaders, cfg.workflow)
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
> > >     epoch_runner(data_loaders[i], **kwargs)
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
> > >     self.call_hook('after_train_iter')
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
> > >     getattr(hook, fn_name)(self)
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/hooks/optimizer.py", line 35, in after_train_iter
> > >     runner.outputs['loss'].backward()
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/tensor.py", line 245, in backward
> > >     torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/autograd/__init__.py", line 147, in backward
> > >     allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
> > >   File "/FisherPruning-Pytorch-main/detection/tools/fisher_pruning_hook/fisher_pruning.py", line 397, in compute_fisher_backward_hook
> > >     runner.run(data_loaders, cfg.workflow)
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
> > >     epoch_runner(data_loaders[i], **kwargs)
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
> > >     self.call_hook('after_train_iter')
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
> > >     getattr(hook, fn_name)(self)
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/hooks/optimizer.py", line 35, in after_train_iter
> > >     runner.outputs['loss'].backward()
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/tensor.py", line 245, in backward
> > >     torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/autograd/__init__.py", line 147, in backward
> > >     allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
> > >   File "/FisherPruning-Pytorch-main/detection/tools/fisher_pruning_hook/fisher_pruning.py", line 397, in compute_fisher_backward_hook
> > >     grads = feature * grad_feature
> > > RuntimeError: The size of tensor a (256) must match the size of tensor b (12) at non-singleton dimension 1
> > >     grads = feature * grad_feature
> > > RuntimeError: The size of tensor a (256) must match the size of tensor b (12) at non-singleton dimension 1
> > > Killing subprocess 35929
> > > Killing subprocess 35930
> > > Traceback (most recent call last):
> > >   File "/anaconda3/envs/fisher/lib/python3.7/runpy.py", line 193, in _run_module_as_main
> > >     "__main__", mod_spec)
> > >   File "/anaconda3/envs/fisher/lib/python3.7/runpy.py", line 85, in _run_code
> > >     exec(code, run_globals)
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
> > >     main()
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
> > >     sigkill_handler(signal.SIGTERM, None)  # not coming back
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
> > >     raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
> > > subprocess.CalledProcessError: Command '['/workdir/maxin/anaconda3/envs/fisher/bin/python', '-u', 'tools/train.py', '--local_rank=1', 'configs/faster_rcnn/faster_pruning.py', '--launch', 'pytorch']' returned non-zero exit status 1.
> > > ```
> > 
> > 
> > torch升级到1.10看看
> 
> @zhaoxin111 Hi, 我升级了之后还是出现该错误，我的环境是：
> 
> * PyTorch: 1.10.1+cu113
> * GCC 7.3
> * CUDA Runtime 11.3
> * CuDNN 8.2
> * TorchVision: 0.11.2+cu113
> 
> 方便展示一下你的环境吗？

你是什么卡呢？

**Comment by Janspiry** [comment]
3080 ti

**Comment by zhaoxin111** [comment]
> 3080 ti

我3090是ok的，我没有3080的卡，没法验证

**Comment by YouAndMe8342** [comment]
> > > > faster-rcnn
> > > 
> > > 
> > > 我跑faster-rcnn的时候遇到了以下的问题，请问下是什么原因呢？我的环境用的是: torch 1.8.0 mmcv 1.3.16 mmdet 2.13.0 torchvision 0.9.0 cudatoolkit 10.2 我同样尝试了mmdet 2.17.0的版本，遇到了相同的错误
> > > ```
> > > Traceback (most recent call last):
> > >   File "tools/train.py", line 195, in <module>
> > > Traceback (most recent call last):
> > >   File "tools/train.py", line 195, in <module>
> > >     main()
> > >   File "tools/train.py", line 191, in main
> > >     main()
> > >   File "tools/train.py", line 191, in main
> > >     meta=meta)
> > >   File "/mmdet/apis/train.py", line 170, in train_detector
> > >     meta=meta)
> > >   File "/mmdet/apis/train.py", line 170, in train_detector
> > >     runner.run(data_loaders, cfg.workflow)
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
> > >     epoch_runner(data_loaders[i], **kwargs)
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
> > >     self.call_hook('after_train_iter')
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
> > >     getattr(hook, fn_name)(self)
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/hooks/optimizer.py", line 35, in after_train_iter
> > >     runner.outputs['loss'].backward()
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/tensor.py", line 245, in backward
> > >     torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/autograd/__init__.py", line 147, in backward
> > >     allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
> > >   File "/FisherPruning-Pytorch-main/detection/tools/fisher_pruning_hook/fisher_pruning.py", line 397, in compute_fisher_backward_hook
> > >     runner.run(data_loaders, cfg.workflow)
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
> > >     epoch_runner(data_loaders[i], **kwargs)
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 51, in train
> > >     self.call_hook('after_train_iter')
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
> > >     getattr(hook, fn_name)(self)
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/mmcv/runner/hooks/optimizer.py", line 35, in after_train_iter
> > >     runner.outputs['loss'].backward()
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/tensor.py", line 245, in backward
> > >     torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/autograd/__init__.py", line 147, in backward
> > >     allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
> > >   File "/FisherPruning-Pytorch-main/detection/tools/fisher_pruning_hook/fisher_pruning.py", line 397, in compute_fisher_backward_hook
> > >     grads = feature * grad_feature
> > > RuntimeError: The size of tensor a (256) must match the size of tensor b (12) at non-singleton dimension 1
> > >     grads = feature * grad_feature
> > > RuntimeError: The size of tensor a (256) must match the size of tensor b (12) at non-singleton dimension 1
> > > Killing subprocess 35929
> > > Killing subprocess 35930
> > > Traceback (most recent call last):
> > >   File "/anaconda3/envs/fisher/lib/python3.7/runpy.py", line 193, in _run_module_as_main
> > >     "__main__", mod_spec)
> > >   File "/anaconda3/envs/fisher/lib/python3.7/runpy.py", line 85, in _run_code
> > >     exec(code, run_globals)
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
> > >     main()
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
> > >     sigkill_handler(signal.SIGTERM, None)  # not coming back
> > >   File "/anaconda3/envs/fisher/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
> > >     raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
> > > subprocess.CalledProcessError: Command '['/workdir/maxin/anaconda3/envs/fisher/bin/python', '-u', 'tools/train.py', '--local_rank=1', 'configs/faster_rcnn/faster_pruning.py', '--launch', 'pytorch']' returned non-zero exit status 1.
> > > ```
> > 
> > 
> > torch升级到1.10看看
> 
> @zhaoxin111 Hi, 我升级了之后还是出现该错误，我的环境是：
> 
> * PyTorch: 1.10.1+cu113
> * GCC 7.3
> * CUDA Runtime 11.3
> * CuDNN 8.2
> * TorchVision: 0.11.2+cu113
> 
> 方便展示一下你的环境吗？

我的环境和你差不多 除了是cuda11.6 还是遇到这个问题 请问你解决了吗

**Comment by YouAndMe8342** [comment]
> > 3080 ti
> 
> 我3090是ok的，我没有3080的卡，没法验证

你好 我的卡是3090 还是遇到了这个维度不匹配的报错 请问可以具体列一下您这边的环境吗

**Comment by zhaoxin111** [comment]
> 

维度不匹配很有可能是反向梯度拓扑图与匹配模式不一致，可以尝试记录一下方向拓扑图，可通过loss一层层回退查看。
